
SIM_DAYS = (12*30) #360 days , one years
SIM_RAND_SEED = 0
SIM_MAX_TRANS_TIMES = 1
SIM_PROGRESS_TIMES_ENABLE = 1
SIM_TRANS_PERCENT = 0.4
SIM_TRANS_ASSET = 0 # default as Unlimited
SIM_TRANS_DAYS_LIMIT = (30*2) #2 month

